#!/bin/bash

sudo pip install --upgrade roscreate
rosinstall --catkin ${WORKSPACE}/src https://raw.github.com/stonier/win_ros/master/mingw_unstable.rosinstall
mkdir -p ${WORKSPACE}/build
mkdir -p ${WORKSPACE}/install
cd ${WORKSPACE}/build
cmake -DCMAKE_INSTALL_PREFIX=~/rosws/install ../src
make
cd ${WORKSPACE}/src
roscreate-stack foo ros_comm std_msgs
cd foo
roscreate-cpp-pkg cfoo
roscreate-pkg tfoo cfoo
roscreate-qt-pkg qfoo
cd tfoo
wget https://raw.github.com/yujinrobot/roscreate/master/jenkins/main.cpp
wget https://raw.github.com/yujinrobot/roscreate/master/jenkins/CMakeLists.txt
cd ..
wget https://raw.github.com/yujinrobot/roscreate/master/jenkins/CMakeLists.stack.txt -O CMakeLists.txt
cd ${WORKSPACE}/build
make
make install



